### during development, uncomment the following
# baseurl = "/"
### during deployment, comment the following
baseurl = "https://web.eecs.umich.edu/~yutongw"


languageCode = "en-us"
title = "Yutong Wang"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/YutongWangUMich/"
    pre = "fab fa-github"
    weight = 1
[[menu.main]]
    name = "CV"
    url = "cv.pdf"
    pre = "fa-regular fa-file"
    weight = 2
[[menu.main]]
    name = "Google Scholar"
    url = "https://scholar.google.com/citations?hl=en&user=GH7ryE4AAAAJ&view_op=list_works&sortby=pubdate"
    pre = "fa-solid fa-graduation-cap"
    weight = 3
    
[params]
    description = "Yutong Wang"
    footer = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
